# Generated by Django 5.0 on 2023-12-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proyect',
            new_name='project',
        ),
    ]
